### ISSUE TITLE
about storedData

### ISSUE THREAD

**Issue by diving16** [RLGC-Project/RLGC#5]
When I run the train files like "trainKundur2areaGenBrakingAgent", "trainIEEE39LoadSheddingAgent_continuous_action_DDPG" or "trainIEEE39LoadSheddingAgent_discrete_action", I found generated npy.files in storedData is 1kB and all the step_* variables like "step_rewards" become [].
Thus I cannot check it as the .ipynb files you provided.
I have already build the environment uses the yml environment.

**Comment by thuang** [comment]
There are some discrepancies as  .ipynb files were not updated and some parts of the callback function in the training *.py files was commented. 

You may follow the stable-baselines (different from OpenAI baselines)  example below to monitor and check the training results.

https://stable-baselines.readthedocs.io/en/master/guide/examples.html#using-callback-monitoring-training
