### ISSUE TITLE
Fail to run this project...

### ISSUE THREAD

**Issue by roki1031** [RLGC-Project/RLGC#7]
Hi, thank you very much for being able to provide such a platform. Here I have some questions to ask about how to successfully run this project.
First of all, I have read in detail about the "READ ME" and have installed Anaconda3 and JDK-1.8 on Ubuntu. But whenever I create the environment I get an error similar to "ResolvePackagesNotFound". I solved this problem through google, but still couldn't run this project. When I follow the instructions in the README, it keeps prompting me with errors like "no module named py4j". (I know this is because this module was not downloaded, but shouldn't this be included in the .yml file?) So I want to ask if I need some other default conditions, such as the configuration or system of the reinforcement learning environment in python Parameter settings, etc.?

**Comment by qhuang-pnl** [comment]
Thanks for your interest and feedback. I exported the env.yml again with no builds. Please try to use this and let me know if it works for you. https://github.com/RLGC-Project/RLGC/blob/master/environment.yml

**Comment by roki1031** [comment]
Thank you for replying to me. I have re-downloaded the entire master folder and tried to run it again. But I still get this giving error. Is there a problem with my anaconda configuration?

`Ran pip subprocess with arguments:
['/home/roki/anaconda3/envs/RL_Challenge/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt']
Pip subprocess output:
Collecting atari-py==0.2.6 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/8f/ba/1d22e9d2f332f07aaa57041f5dd569c2cb40a92bd6374a0b743ec3dfae97/atari_py-0.2.6-cp37-cp37m-manylinux1_x86_64.whl
Collecting click==7.0 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
Collecting cloudpickle==1.2.2 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/c1/49/334e279caa3231255725c8e860fa93e72083567625573421db8875846c14/cloudpickle-1.2.2-py2.py3-none-any.whl
Collecting cycler==0.10.0 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting dill==0.2.9 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/fe/42/bfe2e0857bc284cbe6a011d93f2a9ad58a22cb894461b199ae72cfef0f29/dill-0.2.9.tar.gz
Collecting docutils==0.14 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl (543kB)
Collecting future==0.17.1 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
Collecting glob2==0.6 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/f0/e8/970c7a031b2d7f9a21fefaa8c9d5c38001f8f25055f4ffcb32b3dbecd1ea/glob2-0.6.tar.gz
Collecting gym==0.15.3 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/d2/88/a7186ffe1f33570ad3b8cd635996e5a3e3e155736e180ae6a2ad5e826a60/gym-0.15.3.tar.gz (1.6MB)
Collecting joblib==0.13.2 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/cd/c1/50a758e8247561e58cb87305b1e90b171b8c767b15b12a1734001f41d356/joblib-0.13.2-py2.py3-none-any.whl
Collecting kiwisolver==1.1.0 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/93/f8/518fb0bb89860eea6ff1b96483fbd9236d5ee991485d0f3eceff1770f654/kiwisolver-1.1.0-cp37-cp37m-manylinux1_x86_64.whl (90kB)
Collecting matplotlib==2.2.4 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/98/06/3236cd45dcdc236b38c4c3d94534af918d1e9321ba9fad34d5cfe321ee11/matplotlib-2.2.4-cp37-cp37m-manylinux1_x86_64.whl
Collecting metakernel==0.23.0 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/fc/23/4a6f71b7310f32ad1e1141e6e4fd3f1d87d0e3adb206c451e42dee0f180f/metakernel-0.23.0-py2.py3-none-any.whl
Collecting mpi4py==3.0.1 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/55/a2/c827b196070e161357b49287fa46d69f25641930fd5f854722319d431843/mpi4py-3.0.1.tar.gz
Collecting numpy==1.15.4 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/38/39/f73e104d44f19a6203e786d5204532e214443ea2954917b27f3229e7639b/numpy-1.15.4-cp37-cp37m-manylinux1_x86_64.whl
Collecting oct2py==4.0.6 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/eb/29/929c7a4edb7186f16217fac8494f5ce4565151dc5ed2625c99efc717d34e/oct2py-4.0.6-py2.py3-none-any.whl
Collecting octave-kernel==0.30.3 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/ee/cc/65c1fd6e7507f6dd47c5f7925d45608c1101b9999f25ac13b78d1c91b280/octave_kernel-0.30.3-py3-none-any.whl
Collecting opencv-python==4.1.0.25 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/de/52/61b9619a7a95a8d809515f68f1441224a07ce1873fd3af5e662851014a55/opencv_python-4.1.0.25-cp37-cp37m-manylinux1_x86_64.whl
Collecting pillow==6.0.0 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 19))
  Downloading https://files.pythonhosted.org/packages/c1/e6/ce127fa0ac17775bc7887c432ffe945c49ae141f01b477b7cd5e63b16bb5/Pillow-6.0.0-cp37-cp37m-manylinux1_x86_64.whl (2.0MB)
Collecting pygame==1.9.6 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/18/b3/0bf5afdcf6ef95d2a343cd7865585a6efe5e3e727c1a4f3385c9935248cf/pygame-1.9.6-cp37-cp37m-manylinux1_x86_64.whl
Collecting pyglet==1.3.2 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 21))
  Downloading https://files.pythonhosted.org/packages/1c/fc/dad5eaaab68f0c21e2f906a94ddb98175662cc5a654eee404d59554ce0fa/pyglet-1.3.2-py2.py3-none-any.whl (1.0MB)
Collecting pypower==5.1.4 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 22))
  Using cached https://files.pythonhosted.org/packages/ec/e2/2e3dbb314f08ff0222aba90ada335f18bc3e7a022654d949b0d43f027b88/PYPOWER-5.1.4.tar.gz
Collecting pypownet==2.2.0 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 23))

Pip subprocess error:
  ERROR: Could not find a version that satisfies the requirement pypownet==2.2.0 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 23)) (from versions: none)
ERROR: No matching distribution found for pypownet==2.2.0 (from -r /home/roki/RLGC/condaenv.4s3xx3ad.requirements.txt (line 23))


CondaEnvException: Pip failed
`

**Comment by qhuang-pnl** [comment]
pypower and pypownet is not required for the project, I just removed them. https://github.com/RLGC-Project/RLGC/commit/fa2d80e3176e792ce869a46d92c6e155b12c441d
